### ISSUE TITLE
chokes with .babelrc files

### ISSUE THREAD

**Issue by stephenmathieson** [babel/duo-babel#17]
**.babelrc**

```
{
  "presets": [ "es2015", "react" ],
  "plugins": [
    [
      "transform-react-jsx", {
        "pragma": "element"
      }
    ]
  ]
}
```

output:

```
~/dev/src/github.com/segmentio/icons on master [!] ∴ ./node_modules/.bin/duo --use ./preview/duo-plugins.js index.js 

        using : babel
     building : index.js
        using : compatibility
        using : stoj
        error : Error: [BABEL] /Users/stephenmathieson/dev/src/github.com/segmentio/icons/index.js: Unknown option: /Users/stephenmathieson/dev/src/github.com/segmentio/icons/.babelrc.presets
    at Ware.babel (/Users/stephenmathieson/dev/src/github.com/segmentio/icons/node_modules/duo-babel/index.js:78:13)
    at Ware.<anonymous> (/Users/stephenmathieson/dev/src/github.com/segmentio/icons/node_modules/duo/node_modules/ware/node_modules/wrap-fn/index.js:75:16)
    at Ware.<anonymous> (/Users/stephenmathieson/dev/src/github.com/segmentio/icons/node_modules/duo/node_modules/ware/node_modules/wrap-fn/index.js:57:27)
    at next (/Users/stephenmathieson/dev/src/github.com/segmentio/icons/node_modules/duo/node_modules/ware/lib/index.js:85:20)
    at Ware.run (/Users/stephenmathieson/dev/src/github.com/segmentio/icons/node_modules/duo/node_modules/ware/lib/index.js:88:3)
    at Duo.<anonymous> (/Users/stephenmathieson/dev/src/github.com/segmentio/icons/node_modules/duo/node_modules/thunkify/index.js:43:12)
    at Duo.next (/Users/stephenmathieson/dev/src/github.com/segmentio/icons/node_modules/duo/node_modules/co/index.js:90:21)
    at /Users/stephenmathieson/dev/src/github.com/segmentio/icons/node_modules/duo/node_modules/co/index.js:93:18
    at /Users/stephenmathieson/dev/src/github.com/segmentio/icons/node_modules/duo/node_modules/co-fs/node_modules/thunkify/index.js:28:12
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

but:

```
 ~/dev/src/github.com/segmentio/icons on master [!] ∴ rm .babelrc 

 ~/dev/src/github.com/segmentio/icons on master [!] ∴ ./node_modules/.bin/duo --use ./preview/duo-plugins.js index.js 

        using : babel
     building : index.js
        using : compatibility
        using : stoj
        built : index.js
        wrote : index.js

 ~/dev/src/github.com/segmentio/icons on master [!] ∴ 
```

**Comment by dominicbarnes** [comment]
duo-babel only uses babel@5 atm, it probably needs to be upgraded. However, basically everything about babel changes under the hood when we do that. (will need to redocument using this plugin in light of that)
